version: '2.3'
services:
  programming:
    build:
      context: ..
      target: base
    command: compose/develop
    environment:
      PYTHONPATH: .
    ports:
      - '8080:8080'
    volumes:
      - ..:/app
