version: '2.3'
services:
  zookeeper:
    restart: always
    container_name: zookeeper
    build:
      context: .
      target: base
    command: /code/kafka_2.11-2.0.0/bin/zookeeper-server-start.sh /code/kafka_2.11-2.0.0/config/zookeeper.properties
    networks:
      - backend
    ports:
      - '2181:2181'
  kafka:
    links:
      - zookeeper
    depends_on:
      - zookeeper
    restart: always
    build:
      context: .
      target: base
    volumes:
      - './kafka-storage:/tmp/kafka-logs'
    command: /code/kafka_2.11-2.0.0/bin/kafka-server-start.sh /code/kafka_2.11-2.0.0/config/server.properties
    networks:
      - backend
    ports:
      - '9092:9092'
    container_name: kafka
  kafka2:
    links:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper
      - kafka
    restart: always
    build:
      context: .
      target: base
    volumes:
      - './kafka-storage2:/tmp/kafka-logs'
    command: /code/kafka_2.11-2.0.0/bin/kafka-server-start.sh /code/kafka_2.11-2.0.0/config/server2.properties
    networks:
      - backend
    container_name: kafka2
  kafka3:
    links:
      - zookeeper
      - kafka
      - kafka2
    depends_on:
      - zookeeper
      - kafka
      - kafka2
    restart: always
    build:
      context: .
      target: base
    volumes:
      - './kafka-storage3:/tmp/kafka-logs'
    command: /code/kafka_2.11-2.0.0/bin/kafka-server-start.sh /code/kafka_2.11-2.0.0/config/server3.properties
    networks:
      - backend
    container_name: kafka3
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.1.0
    ports:
      - 8082:8082
    links:
      - kafka
      - zookeeper
      - kafka2
      - kafka3
    depends_on:
      - kafka
      - zookeeper
      - kafka2
      - kafka3
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'http://kafka:9092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    networks:
      - backend
    container_name: kafka-rest
  kafka-landoop:
    image: landoop/kafka-topics-ui
    ports:
      - 8000:8000
    links:
      - kafka
      - zookeeper
      - kafka-rest
      - kafka2
      - kafka3
    depends_on:
      - kafka
      - zookeeper
      - kafka-rest
      - kafka2
      - kafka3
    environment:
      KAFKA_REST_PROXY_URL: "kafka-rest:8082"
      PROXY: "true"
    networks:
      - backend
    container_name: kafka-landoop
  jupyter_notebook:
    build:
      context: jupyter
      target: base
    networks:
      - backend
    command: jupyter notebook --ip=0.0.0.0 --port=8080 --allow-root
    environment:
      PYTHONPATH: .
    ports:
      - '8080:8080'


networks:
  backend:
    external:
      name: isuterkini-backend_default
