version: '2.3'
services:
  processing:
    build:
      context: ..
      target: base
    command: compose/develop
    environment:
      PYTHONPATH: .
    ports:
      - '5000:5000' # flask
    volumes:
      - ..:/app
