version: '2.3'
services:
  processing:
    build:
      context: ..
      target: base
    command: develop/develop
    environment:
      PYTHONPATH: .
    ports:
      - '9300:9300'
      - '9200:9200' # elastic
      - '5000:5000' # flask
