version: '2.3'
services:
  hadoop:
    build:
      context: ..
      target: base
    command: compose/develop
    environment:
      PYTHONPATH: .
    ports:
      - '5000:5000' # flask
      - '8088:8088'
      - '9870:9870'
      - '9864:9864'
      - '19888:19888'
      - '8042:8042'
