version: '2.3'
services:
    zookeeper:
        image: zookeeper:3.4
        container_name: zookeeper
        restart: always

    nimbus:
        build: storm
        container_name: nimbus
        command: storm nimbus
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627
        volumes:
            - ./storm/conf:/conf

    supervisor:
        build: storm
        container_name: supervisor
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always
        volumes:
            - ./storm/conf:/conf

    sui:
        build: storm
        container_name: sui
        command: storm ui
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always
        ports:
            - "8085:8080"
        volumes:
            - ./storm/conf:/conf

    streamparse:
        build: streamparse
        container_name: streamparse
        command: /entrypoint.sh
        depends_on:
            - zookeeper
            - nimbus
            - supervisor
            - sui
        links:
            - zookeeper
            - nimbus
            - supervisor
            - sui
        restart: always
        volumes:
            - ./streamparse/tasks:/tasks
